name: Linting

on:
  pull_request:
    branches_ignore: []

jobs:
  build:
    runs-on: ubuntu-latest
    name: Lint markdown (md)
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: markdownlint-cli2-action
        uses: DavidAnson/markdownlint-cli2-action@v12
        with:
          globs: '**/*.md'
