name: Testing Workflow

on:
  push:
  pull_request:
    branches: [ main ]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DavidAnson/markdownlint-cli2-action@v12
        with:
          # config: ./markdownlint-cli2.jsonc
          globs: "**/*.md"
  conformance:
    name: Conformance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          make conformance
